[package]
name = "state_set_chainlink"
version = "0.1.0"
authors = ["Tekhnae Raav <tekhnaeraav@katharostech.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
bevy = "0.4"
